import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import QueryProvider from '@/components/providers/QueryProvider';
import Header from '@/components/Header';
import UserInit from '@/components/UserInit';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full'
    >
      <body className={`${pretendard.variable} antialiased flex flex-col relative min-h-screen h-full font-pretendard`}>
        <QueryProvider>
          <UserInit />
          <Header />
          <main className='flex-1 px-[20px] flex flex-col h-full pt-[81px] desktop:mt-0'>{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
